# Generated by Django 2.2 on 2022-03-18 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkStatus3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlerror',
            name='checkUrl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkStatus3.CheckUrl'),
        ),
    ]
