# Generated by Django 2.2 on 2022-03-18 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkStatus3', '0003_auto_20220318_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkurl',
            name='errors',
        ),
    ]
